### ISSUE TITLE
Unhandled Exception: PlatformException(Failed to run model, Interpreter busy, java.lang.RuntimeException

### ISSUE THREAD

**Issue by francisrod01** [Muhammad-Ullah/rottenapple#1]
I just ran it and I got an error in the console while the app is capturing apple images, it looks like the predictions against Google images results in the search got a low accuracy.

```
E/flutter ( 4420): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Failed to run model, Interpreter busy, java.lang.RuntimeException: Interpreter busy
E/flutter ( 4420): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.<init>(TflitePlugin.java:450)
E/flutter ( 4420): 	at sq.flutter.tflite.TflitePlugin$RunModelOnFrame.<init>(TflitePlugin.java:545)
E/flutter ( 4420): 	at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:117)
E/flutter ( 4420): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 4420): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 4420): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter ( 4420): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 4420): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 4420): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 4420): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter ( 4420): 	at android.os.Looper.loop(Looper.java:299)
E/flutter ( 4420): 	at android.app.ActivityThread.main(ActivityThread.java:8105)
E/flutter ( 4420): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4420): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter ( 4420): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/flutter ( 4420): , null)
E/flutter ( 4420): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 4420): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 4420): <asynchronous suspension>
E/flutter ( 4420): #2      Tflite.runModelOnFrame (package:tflite/tflite.dart:73:12)
E/flutter ( 4420): <asynchronous suspension>
E/flutter ( 4420): #3      _ModelState.runModel (package:rotten_apple_detection/model.dart:133:26)
E/flutter ( 4420): <asynchronous suspension>
E/flutter ( 4420): 
W/System  ( 4420): A resource failed to call destroy. 
W/System  ( 4420): A resource failed to call destroy. 
W/System  ( 4420): A resource failed to call destroy. 
W/System  ( 4420): A resource failed to call destroy. 
W/System  ( 4420): A resource failed to call destroy. 
E/flutter ( 4420): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Failed to run model, Interpreter busy, java.lang.RuntimeException: Interpreter busy
E/flutter ( 4420): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.<init>(TflitePlugin.java:450)
E/flutter ( 4420): 	at sq.flutter.tflite.TflitePlugin$RunModelOnFrame.<init>(TflitePlugin.java:545)
E/flutter ( 4420): 	at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:117)
E/flutter ( 4420): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 4420): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 4420): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter ( 4420): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 4420): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 4420): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 4420): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter ( 4420): 	at android.os.Looper.loop(Looper.java:299)
E/flutter ( 4420): 	at android.app.ActivityThread.main(ActivityThread.java:8105)
E/flutter ( 4420): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4420): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter ( 4420): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/flutter ( 4420): , null)
E/flutter ( 4420): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 4420): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 4420): <asynchronous suspension>
E/flutter ( 4420): #2      Tflite.runModelOnFrame (package:tflite/tflite.dart:73:12)
E/flutter ( 4420): <asynchronous suspension>
E/flutter ( 4420): #3      _ModelState.runModel (package:rotten_apple_detection/model.dart:133:26)
E/flutter ( 4420): <asynchronous suspension>
E/flutter ( 4420): 
V/time    ( 4420): Inference took 50
```

This is related: https://github.com/shaqian/flutter_tflite/issues/239

**Comment by StanleyAbotsikuma** [comment]
I am currently facing similar challenge

**Comment by Muhammad-Ullah** [comment]
Just run it on real device with almost 4-6gb of ram

**Comment by batistafrancis** [comment]
That's not the case. 
My device has enough power to run any app.
https://www.mi.com/in/product/xiaomi-11i-5g/
